# Generated by Django 3.1.1 on 2021-08-19 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer_portal', '0002_cardealer_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicles',
            old_name='description',
            new_name='rent',
        ),
        migrations.RenameField(
            model_name='vehicles',
            old_name='color',
            new_name='vehichle_number',
        ),
    ]
