# Generated by Django 3.1.1 on 2021-08-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer_portal', '0004_auto_20210819_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='rent',
            field=models.IntegerField(default=0),
        ),
    ]
